all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: localhost
          ansible_connection: local

    databases:
      hosts:
        db1:
          ansible_host: localhost
          ansible_connection: local

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
